### ISSUE TITLE
How to deal with parent zoom?

### ISSUE THREAD

**Issue by san-kumar** [minogin/vue-drag-resize-rotate#1]
Hi,

This is a great component but it stop working properly if the parent element has a zoom applied, .e.g:

    <div style="zoom: 0.5">
          <drr... >
    </div>

Also doesn't work with `transform: scale(0.5 0.5)` on parent element either. Any ideas how to fix this?

Thanks!

**Comment by minogin** [comment]
Could you please provide an example (JSFiddle / CodePen)?

**Comment by minogin** [comment]
When zoom or scale is applied `event.pageX` / `event.pageY` still return non-zoomed coordinates. This issue need a fix from me to detect and apply parent zoom.

As a workaround you can apply scale yourself without using css zoom:
```
<div>
  <drr x="x * scale" y="y * scale" w="w * scale" h="h * scale">
...
```

**Comment by san-kumar** [comment]
Thank yo so much for the workaround! :)
